name: doll
description: Trigger prod build/deploy
filename: cloudbuild.yaml
github:
  owner: josepholiverr
  name: doll 
  push:
    branch: ^prod$
substitutions:
  _REGION: us-central1
  _APP_NAME: TBD
  _BRANCH_NAME: prod
 